import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2b313c",
        "surface-container-low": "#f0f3ff",
        surface: "#f9f9ff",
        outline: "#74777f",
        "surface-container": "#e8eefd",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-variant": "#dde2f2",
        "on-secondary-fixed-variant": "#633f00",
        "on-primary-container": "#8ba5cf",
        "on-secondary-fixed": "#291800",
        "primary-container": "#0b315b",
        "tertiary-container": "#411d00",
        "surface-dim": "#d4dae9",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#2e486c",
        secondary: "#835500",
        background: "#f9f9ff",
        "on-tertiary-fixed-variant": "#683c1a",
        primary: "#08274A",
        "surface-tint": "#465f85",
        "on-secondary-container": "#6e4600",
        "secondary-container": "#FCB242",
        "primary-fixed": "#d5e3ff",
        "surface-container-high": "#e3e8f8",
        "tertiary-fixed": "#ffdcc6",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#ba8159",
        "inverse-primary": "#aec8f3",
        "on-surface": "#161c27",
        "secondary-fixed-dim": "#ffb954",
        "on-tertiary-fixed": "#301400",
        tertiary: "#220c00",
        "on-primary-fixed": "#001c3b",
        "primary-fixed-dim": "#aec8f3",
        "on-background": "#161c27",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffddb4",
        "surface-bright": "#f9f9ff",
        "tertiary-fixed-dim": "#f9b98d",
        "surface-container-highest": "#dde2f2",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#ecf0ff",
        "outline-variant": "#c4c6cf",
        "on-surface-variant": "#43474e",
        error: "#ba1a1a",
        "amber-gold": "#FCB242",
        "deep-navy": "#08274A",
        whatsapp: "#25D366",
        "whatsapp-hover": "#1faa52",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "gutter-desktop": "1.5rem",
        "space-3xl": "4rem",
        "container-max": "1280px",
        "gutter-mobile": "1rem",
        "space-2xl": "3rem",
        "space-xl": "2rem",
        "space-2xs": "0.25rem",
        "space-4xl": "6rem",
        "space-xs": "0.5rem",
      },
      fontFamily: {
        display: ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "code-tech": ["Inter", "sans-serif"],
        "display-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        display: ["56px", { lineHeight: "64px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "code-tech": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "display-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
